analytics: {}
color:
  brandColors:
    - '#080a09'
    - '#32640b'
    - '#69903d'
    - '#bec2ab'
    - '#624732'
  brandStrength: 0.5
  lightness: 0.7072420979384333
  rhythmicContrast: 0.75
  saturation: 0.6875
cta: {}
layout_spectrum: 0.298986
name: PhotoJournal
opengraph: {}
purpose: []
typography_spectrum: 0.271115
