name: PhotoJournal
favicon: null
layout_spectrum: 0.98684
typography_spectrum: 0.3122
title: FSH001 Photo Journal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a09'
    - '#32640b'
    - '#69903d'
    - '#bec2ab'
    - '#624732'
  brandStrength: 0.25
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
